modLoader="javafml"
loaderVersion="[41,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/InfusedFoods/issues"

[[mods]]
	modId="infusedfoods"
	version="${file.jarVersion}"
	displayName="InfusedFoods"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/infusedfoods.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/infused-foods"
	logoFile="banner.png"
	credits="Apex - Programming, FantasyGaming - Texture Artist"
	authors="Apex, FantasyGaming"
	description="Add the ability to apply potion effects to foods."

[[dependencies.infusedfoods]]
	modId="forge"
	mandatory=true
	versionRange="[41.0.98,)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.infusedfoods]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19,1.20)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.infusedfoods]]
	modId="commonality"
	mandatory=true
	versionRange="[2.0.0,3.0.0)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.infusedfoods]]
	modId="apexcore"
	mandatory=true
	versionRange="[5.2.1,6.0.0)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.infusedfoods]]
	modId="jei"
	mandatory=false
	versionRange="[11.0.0.211,)"
	ordering="AFTER"
	side="BOTH"