modLoader="javafml"
loaderVersion="[4,)"
license="AllRightsReserved"

[[mods]]
    modId="infusedfoods"
    version="${file.jarVersion}"
    displayName="InfusedFoods"
    credits="Apex - Programming, Fantasy - Artist"
    authors="ApexStudios"
    description="Infused Foods allows players to infuse food items with Potion Effects."
    logoFile="logo.png"
    displayURL="https://modrinth.com/mod/infused-foods"

[[dependencies.infusedfoods]]
    modId="apexcore"
    type="required"
    versionRange="[21.4,)"

#[[accessTransformers]]
#    file="META-INF/accesstransformer.cfg"
#[[mixins]]
#    config="META-INF/infusedfoods.mixins.json"
