license = "AllRightsReserved"
issueTrackerURL = "https://github.com/ApexStudios-Dev/Issues/issues"

[[mods]]
modId = "infusedfoods"
version = "${file.jarVersion}"
displayName = "InfusedFoods"
credits = "Apex - Programming, Fantasy - Artist"
authors = "ApexStudios"
description = "Infused Foods allows players to infuse food items with Potion Effects."
bannerFile = "banner.png"
iconFile = "icon.png"
displayURL = "https://modrinth.com/mod/infused-foods"

[[dependencies.infusedfoods]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,26.3)"
ordering = "NONE"
side = "BOTH"
[[dependencies.infusedfoods]]
modId = "neoforge"
type = "required"
versionRange = "[26.2-alpha,26.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.infusedfoods]]
modId = "apexcore"
type = "required"
versionRange = "[26.2,26.3)"
[dependencies.infusedfoods.mc-publish]
modrinth = "xl3myxch"
curseforge = "550778"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
[[mixins]]
config="META-INF/infusedfoods.mixins.json"