name: Publish

on:
    workflow_dispatch:
    push:
        branches: [ "**/main" ]
        paths: [ "**/src/**" ]

jobs:
    publish:
        name: Publish InfusedFoods
        uses: ApexStudios-Dev/.github/.github/workflows/publish-mod.yml@master
        secrets: inherit
        with:
            display_name: InfusedFoods
            logo_url: https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/minecraft/new/infused_foods.png
            color: 0x7A4DAF
            release_type: alpha
            artifact_id: infusedfoods
            curseforge_id: "629292"
            modrinth_id: QinxcGwM
